---


- name: get a fun fact!
  hosts: localhost
  tasks:
  - debug:
      msg: "{{ lookup('fun_fact', 'random') }}"

- name: do the thing!
  hosts: localhost
  tasks:
  - debug:
      msg: "Current branch status is: {{ lookup('github-status', 'ansible/ansible', branch='devel') }}!"
