---


- name: get a fun Chuck Norris fact!
  hosts: localhost
  tasks:
  - debug:
      msg: "{{ lookup('fun_fact') }}"

- name: look up github status for ansible
  hosts: localhost
  tasks:
  - debug:
      msg: "Current branch status is: {{ lookup('github_status', 'ansible/ansible', branch='devel') }}!"
